### ISSUE TITLE
Add interpolation of chi^2 for best fit

### ISSUE THREAD

**Issue by slwatkins** [ucbpylegroup/QETpy#6]
An option for ofamp should be added that fits a parabola to the best fit chi^2 and the two adjacent points such that the minimum of the parabola is a better estimating of the fit. This is a way of getting around the limitation of the digitization.

**Comment by william-page** [comment]
some code to do this being used for the nsmb here: https://github.com/ucbpylegroup/QETpy/blob/6aaf5dfe60baa128477de79a16595ccba377beb9/qetpy/core/_of_nsmb.py#L1084

This implementation, which calls np.polyfit, is inferior to an implementation that precomputes the matrix for the quadratic fit. I'm pointing it out as a starting point, to save some docstring writing, and so that we update the nsmb code once a faster interpolation function is written.
